[[redirects]]
  from = "/api/contact"
  to = "https://sendmail2.netlify.app/api/contact"
  status = 301
  force = false
  query = {path = ":path"}  

[[redirects]]
  from = "/api/contact"
  to = "https://sendmail2.netlify.app/api/contact"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  